// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "your region",
  aws_cognito_identity_pool_id:
    "your aws_cognito_identity_pool_id",
  aws_cognito_region: "your region",
  aws_user_pools_id: "your user pool id",
  aws_user_pools_web_client_id: "your aws_user_pools_web_client_id",
  aws_user_files_s3_bucket:
    "your aws_user_pools_web_client_id",
  aws_user_files_s3_bucket_region: "ap-northeast-1",
  aws_appsync_graphqlEndpoint:
    "your https://your end point .appsync-api.ap-northeast-1.amazonaws.com/graphql",
  aws_appsync_region: "ap-northeast-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS"};

export default awsmobile;
