// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-northeast-1",
  aws_cognito_identity_pool_id:
    "ap-northeast-1:9abb0d98-4fb3-461c-b67f-9d755e52b65f",
  aws_cognito_region: "ap-northeast-1",
  aws_user_pools_id: "ap-northeast-1_fqMQkthD1",
  aws_user_pools_web_client_id: "7ceqhp78g29nu6tvshiim1po1t",
  aws_user_files_s3_bucket:
    "awsamplifyvuemaster711f47d1545e4ef6afbc4930448e68e3",
  aws_user_files_s3_bucket_region: "ap-northeast-1",
  aws_appsync_graphqlEndpoint:
    "https://nuxfyqjki5dt5dhfwflmjzli74.appsync-api.ap-northeast-1.amazonaws.com/graphql",
  aws_appsync_region: "ap-northeast-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS"};

export default awsmobile;
